---
title: "First Knit"
author: "Dominic Lima"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: '5'
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I went to Little rock highschool for one year. polytechnic high school for my first three years. I love math and history. My favorite thing about math is that it is easier to understand then anything else for me. My overall best subject is math. My other favorite subject is history as I enjoy to know what has happen but enjoy more doing my own research where i get to see the darker past.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a windows laptop msi ge76. My knowledge of laptops is around the 7 as i know enough to get around programs and figure them out but not much of a geek. More of a geek with cars then computers. My knowledge of laptop comes from what my uncle has taught me which is a lot.My internet access is great and always have good connection usually throughout the year. My internet is usually strong despite living in Lake los Angeles.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  My name is Dominic and some of my friends call me Dom. I don't really care what nickname is given to me. Im not too picky. My overall favorite nickname would be Dom or DomDom. Doesn't matter what my friends or instructors want to call me. I can't say much about this question in a longer explanation because I don't mind any name nor does any name bother me.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to become a fund manager in the future as my dream job and that is why I am taking economics as my major. My greatest interest would be calculus as it will test my knowledge and commit power. I am trying to achieve a economics degree. That is what I am majoring but have thoughts of trying out areospace engineering because it seems interesting. I will stick to economics as my major but If I ever chnage my mind about my major it would be areospace as a close second.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  Ive never traveled aywhere in my life but I would probably visit japan to see the car cultural over there. I am big into cars and seeing the cars that they have over there and their own unique style of creating their own cars is different then ours in America. Only Japan calls my attention at the current moment and nothing else just because of the car scene. I have never been in the military but if forced to join then would have to be the marines as that calls my attention the most. Overall though none of military force calls my attention. The only authory job that calls my attention would be becoming a cop or FBI but that isn't apart of the military.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
  I am taking Math 116. I did not know that 116 covered that much in college but it is a added benefite of taking this class then. None the less this class will help me move forward with my college degree. I am trying to get a bare minum of C or above but will be trying to get at least an B. Just to have a higher gpa score to transfer into a universty. My reasons for taking math 116 is because other math classes were taken and this one was open. While being recommend to me by my counselor. 
 






  




